export const paintingData = [
  // Front Wall
  {
    imgSrc: '3D-art-gallery/artworks/1.jpg',
    width: 5,
    height: 3,
    position: { x: -15, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: 'Starry Night Over the Rhône',
      artist: 'Vincent van Gogh',
      description: 'A calm, starlit night reflected in the Rhône River, conveying both peace and emotional depth.',
      year: '1888',
      link: 'https://en.wikipedia.org/wiki/Starry_Night_Over_the_Rh%C3%B4ne',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/2.jpg',
    width: 5,
    height: 3,
    position: { x: -5, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: 'Sorrowing Old Man ("At Eternity\'s Gate")',
      artist: 'Vincent van Gogh',
      description: 'An elderly man in deep grief, representing human despair and existential struggle.',
      year: '1890',
      link: 'https://en.wikipedia.org/wiki/At_Eternity%27s_Gate_(painting)',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/3.jpg',
    width: 5,
    height: 3,
    position: { x: 5, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: 'Wheatfield with Crows',
      artist: 'Vincent van Gogh',
      description: 'A turbulent sky over a golden wheat field, often seen as a symbol of Van Gogh’s inner turmoil.',
      year: '1890',
      link: 'https://en.wikipedia.org/wiki/Wheatfield_with_Crows',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/4.jpg',
    width: 5,
    height: 3,
    position: { x: 15, y: 2, z: -19.5 },
    rotationY: 0,
    info: {
      title: 'Café Terrace at Night',
      artist: 'Vincent van Gogh',
      description: 'A lively café scene under a vibrant night sky, painted with Van Gogh’s signature brushstrokes.',
      year: '1888',
      link: 'https://en.wikipedia.org/wiki/Caf%C3%A9_Terrace_at_Night',
    },
  },

  // Back Wall
  {
    imgSrc: '3D-art-gallery/artworks/5.jpg',
    width: 5,
    height: 3,
    position: { x: -15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: 'The Bedroom',
      artist: 'Vincent van Gogh',
      description: 'A personal look into Van Gogh’s bedroom in Arles, painted to convey restfulness and simplicity.',
      year: '1888',
      link: 'https://en.wikipedia.org/wiki/Bedroom_in_Arles',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/6.jpg',
    width: 5,
    height: 3,
    position: { x: -5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: 'The Night Café',
      artist: 'Vincent van Gogh',
      description: 'A harshly lit café interior, evoking loneliness and mental unrest through intense color contrasts.',
      year: '1888',
      link: 'https://en.wikipedia.org/wiki/The_Night_Caf%C3%A9',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/7.jpg',
    width: 5,
    height: 3,
    position: { x: 5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: 'Wheatfield Under Thunderclouds',
      artist: 'Vincent van Gogh',
      description: 'A vast, dramatic landscape beneath a stormy sky, representing tension and solitude.',
      year: '1890',
      link: 'https://en.wikipedia.org/wiki/Wheatfield_Under_Thunderclouds',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/8.jpg',
    width: 5,
    height: 3,
    position: { x: 15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: 'Fishing Boats on the Beach at Saintes-Maries',
      artist: 'Vincent van Gogh',
      description: 'Brightly painted fishing boats resting on the shore, capturing a quiet seaside moment.',
      year: '1888',
      link: 'https://en.wikipedia.org/wiki/Fishing_Boats_on_the_Beach_at_Saintes-Maries',
    },
  },

  // Left Wall
  {
    imgSrc: '3D-art-gallery/artworks/9.jpg',
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: -15 },
    rotationY: Math.PI / 2,
    info: {
      title: 'The Yellow House',
      artist: 'Vincent van Gogh',
      description: 'Van Gogh’s home in Arles, where he dreamed of building a community of artists.',
      year: '1888',
      link: 'https://en.wikipedia.org/wiki/The_Yellow_House',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/10.jpg',
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: -5 },
    rotationY: Math.PI / 2,
    info: {
      title: 'Banks of the Seine',
      artist: 'Vincent van Gogh',
      description: 'A peaceful riverside scene painted in Paris, showing early signs of Van Gogh’s evolving style.',
      year: '1887',
      link: 'https://en.wikipedia.org/wiki/Vincent_van_Gogh_paintings_1886–1887#Banks_of_the_Seine',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/11.jpg',
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: 5 },
    rotationY: Math.PI / 2,
    info: {
      title: 'Bridges Across the Seine at Asnières',
      artist: 'Vincent van Gogh',
      description: 'Urban bridges under sunlight, painted with light colors and dynamic brushwork during his Paris stay.',
      year: '1887',
      link: 'https://en.wikipedia.org/wiki/Bridges_across_the_Seine_at_Asni%C3%A8res',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/12.jpg',
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: 15 },
    rotationY: Math.PI / 2,
    info: {
      title: 'The Sower',
      artist: 'Vincent van Gogh',
      description: 'A symbolic depiction of a farmer sowing seeds beneath a burning sun — a cycle of life and hope.',
      year: '1888',
      link: 'https://en.wikipedia.org/wiki/The_Sower_(Van_Gogh)',
    },
  },

  // Right Wall
  {
    imgSrc: '3D-art-gallery/artworks/13.jpg',
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: -15 },
    rotationY: -Math.PI / 2,
    info: {
      title: 'The Harvest',
      artist: 'Vincent van Gogh',
      description: 'A summer harvest scene full of light and color, capturing the essence of southern France.',
      year: '1888',
      link: 'https://en.wikipedia.org/wiki/The_Harvest_(Van_Gogh)',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/14.jpg',
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: -5 },
    rotationY: -Math.PI / 2,
    info: {
      title: 'Reaper in a Wheatfield',
      artist: 'Vincent van Gogh',
      description: 'A solitary reaper at work, symbolizing the eternal cycle of life and death.',
      year: '1889',
      link: 'https://en.wikipedia.org/wiki/Vincent_van_Gogh#Saint-R%C3%A9my_(1889%E2%80%931890)',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/15.jpg',
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: 5 },
    rotationY: -Math.PI / 2,
    info: {
      title: 'The Thresher',
      artist: 'Vincent van Gogh',
      description: 'A vivid rural scene focused on manual labor and the agrarian lifestyle.',
      year: '1889',
      link: 'https://www.vangoghmuseum.nl/en/collection/s0117V1962',
    },
  },
  {
    imgSrc: '3D-art-gallery/artworks/16.jpg',
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: 15 },
    rotationY: -Math.PI / 2,
    info: {
      title: 'Orchard in Blossom',
      artist: 'Vincent van Gogh',
      description: 'An idyllic spring scene of blossoming trees, expressing joy and renewal.',
      year: '1888',
      link: 'https://en.wikipedia.org/wiki/Orchard_in_Blossom',
    },
  },
];
